server:
  port: 8085
spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PiyanKotrey/config-server-kak-micro
          clone-on-start: true