spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_service
      database: product_service

##config-client
#  config:
#    import: optional:configserver:http://localhost:8085
#  profiles:
#    active: dev
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0
